version: '3'

services:
  web:
    build:
      context: .
      args:
        - MIX_ENV=${MIX_ENV:-dev}
    image: hoyley/spot-on:latest
    environment:
      PGUSER: ${PGUSER:-postgres}
      PGPASSWORD: ${PGPASSWORD:-postgres}
      PGDATABASE: ${PGDATABASE:-spot-on}
      PGPORT: ${PGPORT:-5432}
      PGHOST: ${PGHOST:-db}
      HTTP_PORT: ${HTTP_PORT:-8080}
      URL_HOST: ${URL_HOST:-localhost}
      URL_PORT: ${URL_PORT:-80}
    ports:
      - "8080:8080"
      - "80:80"
    depends_on:
      - db
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
